### ISSUE TITLE
Not only Volksbank but also BBBank 

### ISSUE THREAD

**Issue by mist** [Unbrick/VRXposed#1]
I am using the BBBank app which is also by fiducia and after the last upgrade I couldn't use it anymore. But this module works like a charm because it just checks for a part of the name of the package not the whole name. 

So if you could add my bank to the description I'd be really happy! Thanks so much for this module!

**Comment by Unbrick** [comment]
Oh well, i just looked it up and they are using the exact same implementation as they do in the Volksbank application...including the tag "debugwithoutpronom" which i'm overriding. 

Glad to help you, adding it to the description in a second. Thank you very much for this information!

**Comment by Unbrick** [comment]
Added it to the description and changed the name in the xposed repo, thanks! 👍
