### ISSUE TITLE
VR-Banking doesn't start

### ISSUE THREAD

**Issue by timi35** [Unbrick/VRXposed#3]
The app of the German bank Raifeissenbank - vr-banking, doesn't start since the last update. Could you fix it with your modul again?
Thanks.

**Comment by 256FF** [comment]
Same here. Version 16.25.00 closes immediately after starting.

**Comment by Unbrick** [comment]
I have one version of a working VRXposed which should do the trick. Problem right there is: Some app functionality is disabled because big parts of the anti-anti-xposed framework is ripped out. But i can't say what it exactly is, i mainly use the app to check my balance ^^

**Comment by timi35** [comment]
Hi, I use it for checking too. Where can I find the new version. The last 
one doesn't work after the new update of the banking app.

Thanks.


Am 5. April 2017 4:44:06 PM schrieb Unbrick <notifications@github.com>:

**Comment by Unbrick** [comment]
I haven't released the new version to public yet as it's one of the most unstructured code I've ever written. I can make it ready for a release tomorrow and push a release but as I said, there is quite a good chance that some functions aren't working.

I'm planning to write a clean c hook for all pronom-based Xposed checks but this could take a while.

**Comment by Unbrick** [comment]
Just released the Version 1.0.1-dirty, should do the trick!

**Comment by timi35** [comment]
The dirty version works fine for me.

Yesterday a new banking app version was available, and your dirty version works with it too.

Thanks.

 

Von: Unbrick [mailto:notifications@github.com] 
Gesendet: Donnerstag, 6. April 2017 22:29
An: Unbrick/VRXposed
Cc: timi35; Author
Betreff: Re: [Unbrick/VRXposed] VR-Banking doesn't start (#3)

 

Just released the Version 1.0.1-dirty, should do the trick!
