### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jupa** [Unbrick/VRXposed#5]
Okay, im pretty late to the party but your module is sadly not working anymore. Update please. I don't want to uninstall Xposed.

regards

Nice Quizduell Module you made there, thanks!

**Comment by Unbrick** [comment]
Hi @JuPa

sorry for the late response. Sadly it's currently quite difficult to circumvent their protection. The circumvention I did in this module based was based on a quite shitty implementation of the Anti-xposed framework. As they updated their implementation it would take quite a lot of work to get around the framework. 

You currently have two different options:
- going back to a (way) older version of the VRBank application where my hook still works
- or you could use a different banking app, there are several trusted applications on the play store which also support the Volksbank online banking

I'm currently using Numbrs (yes I know, data protection and so on) but it doesn't complain about Xposed and works!  

And glad to hear the QDXposed is appreciated!

**Comment by Unbrick** [comment]
Try using MagiskHide, for me it worked like a charm!
