### ISSUE TITLE
May be it still possible...

### ISSUE THREAD

**Issue by Senliast** [Unbrick/VRXposed#6]
I know, that Volsbank upgraded their protection and its not easy to get
the app started with Xposed. But it must still be a way to do it. I mean, the VR App
is non-root app, that runs with normal permissions and the module runs with
system permissions. May be you can make an image of the variables / values
that are passed to that app normal, if no xposed installed and pass them allways or hide
the props that app is checking. I am sure, there is a way to do it.

If you have time, may be you can try it again? Thanks a lot.

**Comment by Unbrick** [comment]
Try using MagiskHide, for me it worked like a charm!

**Comment by Senliast** [comment]
Hey, It worked for me for some time with magisk Hide and root cloack, after recent ROM and gapps update it doesn't work anymore... The shitty app detects root again. Could you please please take a look into it? So it had something to do with GAPPS / Android itself. Android somehow helps the app to detect root. Earlier it was open gapps beta for Android 10, now it's stable. The app itself didn't update, nor magisk updated. Using Android 10 with EdXposed

**Comment by Unbrick** [comment]
What is your safety net status? Does MagiskHide work properly in other applications?

**Comment by Senliast** [comment]
SafetyNet passes. Magisk Hide works for other apps, I checked and they still not detect root.
